apps/medicamentar-desktop/package-lock.json
apps/medicamentar-desktop/src/components/CardHome.tsx
apps/medicamentar-desktop/src/pages/Home.tsx
apps/medicamentar-desktop/src/pages/auth/SignIn.tsx
apps/medicamentar-desktop/src/pages/pagesData.tsx

Nova tela Home adicionada, e um novo componente criado. Usei o useNavigate para conseguir ir e voltar da nova página, e usei o componente Grid do Material UI para conseguir fazer o layout dos CardHome. Também adicionei a nova tela ao pagesData, e usei o botão entrar da página de login para conseguir entrar na pagina Home.

feat: Tela home e componente CardHome adicionado

---

apps/medicamentar-desktop/src/components/CardHome.tsx
apps/medicamentar-desktop/src/components/SideBar.tsx
apps/medicamentar-desktop/src/pages/Home.tsx

- Primeira versão da SideBar implementada na Home.
-  Está SEM RESPONSIVIDADE. Será encaminhada juntamente com a responsividade dos Cards.
- Ícones da SideBar EM PLANEJAMENTO para maior fidelidade ao protótipo.

feat: Componente SideBar

---

apps/medicamentar-api/pom.xml
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/api/controller/AuthController.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/api/controller/HelloWorldController.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/DTOs/AuthDto/LoginRequest.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/DTOs/AuthDto/RegisterRequest.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/DTOs/ServiceResponse.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/domain/entities/User.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/domain/repositories/UserRepository.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/infrastructure/security/CustomUserDetailsService.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/infrastructure/security/SecurityConfig.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/infrastructure/security/SecurityFilter.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/infrastructure/security/TokenService.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/swagger/SwaggerConfiguration.java
apps/medicamentar-api/src/main/resources/application.properties

- Add auth com Spring Security e JWT #21

feat: adiciona autenticação do usuário

---

apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/api/controller/AuthController.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/api/controller/MedicationController.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/DTOs/AuthDto/LoginRequest.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/DTOs/AuthDto/RegisterRequest.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/DTOs/MedicationDto/MedicationRequest.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/DTOs/MedicationDto/MedicationResponse.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/DTOs/MedicationDto/UpdateRequest.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/DTOs/ServiceResponse.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/services/MedicationService.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/domain/entities/Medication.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/domain/repositories/MedicationRepository.java

#22 Adiciona o CRUD de medicamentos.

feat: Adiciona o CRUD de medicamentos.

---

apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/api/controller/ExamController.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/DTOs/ExamDto/ExamRequest.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/services/ExamService.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/domain/entities/Exam.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/domain/repositories/ExamRepository.java

#26 Faz os endpoints para o gerenciamento de exames

feat: adiciona o crud de exames

---

apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/api/controller/ConsultationController.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/api/controller/MedicationController.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/DTOs/ConsultationDto/ConsultationRequest.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/DTOs/ConsultationDto/ConsultationResponse.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/services/ConsultationService.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/domain/entities/Consultation.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/domain/repositories/ConsultationRepository.java

Adiciona as funções de Criar, Exibir e Deletar uma consulta: #19

feat: Adiciona endpoints de consultas.

---

apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/api/controller/ConsultationController.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/api/controller/MedicationController.java

#32 
Corrige os endpoints de:
- ConsultationController
- MedicationController

fix: corrige os endpoints retirando a '/' de dentro dos '{ }'

---

apps/medicamentar-desktop/src/components/CardMedicine.tsx
apps/medicamentar-desktop/src/components/ModalDelete.tsx
apps/medicamentar-desktop/src/pages/Home.tsx

- Adicionado novo componente de card para exibir medicamentos
- Implementado modal customizado para exclusão de medicamentos
- Ajustada responsividade do grid na tela Home para melhor visualização
Fix:
- [Card Medicamento #50]
- [Modal - Deletar Medicamento #38]

feat: componente de card, modal delete criado e responsividade do grid da tela home (#38, #50)

---

apps/medicamentar-desktop/public/assets/icons/Add_Icon.tsx
apps/medicamentar-desktop/src/components/SideBar.tsx
apps/medicamentar-desktop/src/pages/Medicine.tsx
apps/medicamentar-desktop/src/pages/pagesData.tsx

- Adicionado a tela de Medicamentos com roteamento pela SideBar.
- Adicionado título e botão "Adicionar Medicamento"
- Responsividade inicialmente funcional.

feat: Tela Medicamentos. Close #49

---

apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/api/controller/MedicationController.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/dtos/authDto/MedicationRequest.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/dtos/medicationDto/MedicationRequest.java
apps/medicamentar-api/src/main/resources/application.properties

Validação #58 
adição da validação do requestMedicamentation e o valid

Adição da validação do requestMedicamentation e o valid

---

apps/medicamentar-desktop/package-lock.json
apps/medicamentar-desktop/package.json
apps/medicamentar-desktop/src/components/ExamModal.tsx
apps/medicamentar-desktop/src/components/SideBar.tsx
apps/medicamentar-desktop/src/pages/Exam.tsx
apps/medicamentar-desktop/src/pages/pagesData.tsx

1. Modal Introduzido(Falta fazer algumas alterações)
2. Pagina Consulta e exames criada porém falta fazer algumas alterações
#34 #12

Criação da page consulta e exames e introdução do modal 

---

apps/medicamentar-api/src/main/resources/application.properties
apps/medicamentar-desktop/electron/main.ts
apps/medicamentar-desktop/src/components/CardMedicine.tsx
apps/medicamentar-desktop/src/components/MedicineTypeModal.tsx
package.json
run_desktop.sh

- cria um bashscript que roda a UI e a API
- repara erros de build
- remove imports quebrados

Criab ash script para ambiente desktop

---

apps/medicamentar-desktop/src/components/SideBar.tsx
apps/medicamentar-desktop/src/pages/Config.tsx
apps/medicamentar-desktop/src/pages/pagesData.tsx

feat: implementando tela de configurações

---

apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/api/controller/ExamController.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/dtos/examDto/ExamRequest.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/dtos/examDto/ExamResponse.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/dtos/medicationDto/MedicationRequest.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/services/ExamService.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/domain/repositories/ExamRepository.java

Adiciona as validações dos endpoits de Exams

---

apps/medicamentar-desktop/src/components/CardUniversal.tsx
apps/medicamentar-desktop/src/components/Modals/ModalEditMedicine.tsx
apps/medicamentar-desktop/src/pages/Home.tsx
apps/medicamentar-desktop/src/pages/Medicine.tsx

Unificação dos cards: CardMedicine e CardHome. Melhorias de responsividade.
Closes #79

Refactor: CardUniversal

---

apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/api/controller/EventLogController.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/dtos/eventsHistoryDto/EventLogResponse.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/services/ConsultationService.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/services/EventLogService.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/services/ExamService.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/services/MedicationService.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/domain/entities/EventLog.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/domain/enums/EventLogAction.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/domain/repositories/EventLogRepository.java

feat: adiciona o histórico de eventos

---

apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/api/controller/AuthController.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/dtos/authDto/LoginRequest.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/dtos/authDto/RegisterRequest.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/dtos/responsesDto/PaginatedResponse.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/dtos/responsesDto/ServiceResponse.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/services/AuthService.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/services/EventService.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/services/PasswordResetService.java

fix: corrige a validação de alguns campos e respostas

---

apps/medicamentar-desktop/src/components/CardUniversal.tsx
apps/medicamentar-desktop/src/components/Modals/ModalDelete.tsx
apps/medicamentar-desktop/src/pages/Home.tsx
apps/medicamentar-desktop/src/pages/Medicine.tsx

ModalDelete, CardUniversal e Medicine, foram alterados para conseguirmos deletar os cards de medicamentos
A tela Medicine já está ligada com a API de medication.

feat: Exclusão de medicamentos e Listagem de Medicamentos da API

---

apps/medicamentar-desktop/electron/main.ts
apps/medicamentar-desktop/src/components/ContainerUniversal.tsx
apps/medicamentar-desktop/src/components/Header.tsx
apps/medicamentar-desktop/src/components/Modals/ModalNewMedication.tsx
apps/medicamentar-desktop/src/components/SectionContainer.tsx
apps/medicamentar-desktop/src/components/SideBar.tsx
apps/medicamentar-desktop/src/pages/Config.tsx
apps/medicamentar-desktop/src/pages/Exam.tsx
apps/medicamentar-desktop/src/pages/History.tsx
apps/medicamentar-desktop/src/pages/Home.tsx
apps/medicamentar-desktop/src/pages/Medicine.tsx
apps/medicamentar-desktop/src/pages/Profile.tsx
apps/medicamentar-desktop/src/pages/auth/ForgotPassword.tsx
apps/medicamentar-desktop/src/pages/auth/Register.tsx
apps/medicamentar-desktop/src/pages/auth/ResetPassword.tsx
apps/medicamentar-desktop/src/pages/auth/SignIn.tsx

- Corrige h1's aninhados de maneira incorreta
- Ajusta responsividade de paginas relatas
- Refatora estilização inconsistente das telas
- Reforça padronização de componentes

Ajustes em responsividade

---

apps/medicamentar-desktop/src/pages/auth/Register.tsx
apps/medicamentar-desktop/src/pages/auth/SignIn.tsx
apps/medicamentar-desktop/src/utils/handleCapslock.ts
apps/medicamentar-desktop/src/utils/handleShowPassword.ts

- Foi adicionado feedback visual nos campos de senha quando a tecla CapsLock do usuário está ativada
- Foi adicionado uma checkbox de "mostrar senha" que quando ligada revela a senha no formulário
Ambas adições  foram feitas nas telas de Registro e Login.

feat: Adicionando feedback visual nos formulários

---

apps/medicamentar-desktop/src/components/CardUniversal.tsx
apps/medicamentar-desktop/src/components/Modals/ExamModal.tsx
apps/medicamentar-desktop/src/pages/Exam.tsx
apps/medicamentar-desktop/src/pages/Home.tsx
apps/medicamentar-desktop/src/pages/Medicine.tsx

- Exibindo os cards de consultas na tela exam.
- Alteração de algumas variáveis para conseguir obter os dados da API

feat: Exibindo Exames e Consultas na tela de Exam

---

apps/medicamentar-desktop/src/pages/Exam.tsx
apps/medicamentar-desktop/src/pages/Home.tsx
apps/medicamentar-desktop/src/pages/Medicine.tsx

Implementa paginação

---

apps/medicamentar-desktop/electron/main.ts
apps/medicamentar-desktop/electron/preload.ts
apps/medicamentar-desktop/src/electron.d.ts
apps/medicamentar-desktop/src/hooks/AuthContext.tsx

@dodojoy 
Implementa sistema de notificações para eventos e medicações [ #114 ]

Implementa notificações aos eventos

---

apps/medicamentar-desktop/src/constants/theme/ThemeProvider.tsx
apps/medicamentar-desktop/src/pages/History.tsx

Agora o tema que o usuário está utilizando sempre irá permanecer em uso, independente se o programa for fechado.

feat: Adicionando funcionalidade de guardar tema

---

apps/medicamentar-desktop/.env.example
apps/medicamentar-desktop/src/components/CardUniversal.tsx
apps/medicamentar-desktop/src/components/Modals/ExamEditModal.tsx
apps/medicamentar-desktop/src/components/Modals/ModalEditMedicine.tsx
apps/medicamentar-desktop/src/components/Modals/ModalMedicineType.tsx
apps/medicamentar-desktop/src/components/Modals/ModalNewMedication.tsx
apps/medicamentar-desktop/src/pages/Exam.tsx
apps/medicamentar-desktop/src/pages/Medicine.tsx
pnpm-lock.yaml

feat: Correção do Modal Medicamento #74 

---

apps/medicamentar-desktop/src/App.tsx
apps/medicamentar-desktop/src/components/CardUniversal.tsx
apps/medicamentar-desktop/src/components/GridItem.tsx
apps/medicamentar-desktop/src/components/Modals/ExamEditModal.tsx
apps/medicamentar-desktop/src/components/Modals/ExamModal.tsx
apps/medicamentar-desktop/src/components/Modals/ModalEditMedicine.tsx
apps/medicamentar-desktop/src/components/Modals/ModalNewMedication.tsx
apps/medicamentar-desktop/src/pages/Exam.tsx
apps/medicamentar-desktop/src/pages/History.tsx
apps/medicamentar-desktop/src/pages/Home.tsx
apps/medicamentar-desktop/src/pages/Medicine.tsx
apps/medicamentar-desktop/src/pages/Profile.tsx
apps/medicamentar-desktop/src/pages/auth/SignIn.tsx

Paginação e limpeza de logs

---

apps/medicamentar-desktop/src/components/CardUniversal.tsx
apps/medicamentar-desktop/src/pages/History.tsx
apps/medicamentar-desktop/src/types/sanitizeDate.ts

feat: formatação de datas nos Cards

---

apps/medicamentar-desktop/src/components/Feedback.tsx
apps/medicamentar-desktop/src/components/Modals/ExamEditModal.tsx
apps/medicamentar-desktop/src/components/Modals/ExamModal.tsx
apps/medicamentar-desktop/src/components/Modals/ModalEditMedicine.tsx
apps/medicamentar-desktop/src/components/Modals/ModalNewMedication.tsx
apps/medicamentar-desktop/src/pages/Exam.tsx
apps/medicamentar-desktop/src/pages/Medicine.tsx

Resolve erros de duplicações de código, e melhora o feedback  após as utilizações de formulários e adiciona validações em formulários

fix: resolve erros melhora feedback e validações de formulários

---

apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/dtos/userDto/UserResponse.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/services/UserService.java
apps/medicamentar-desktop/package-lock.json
apps/medicamentar-desktop/src/pages/Profile.tsx

- Implementa a funcionalidade da página perfil: Alterar e Salvar nome, idade, peso, etc.
- Acrescimo de "Weigth" nas requisições do Swagger.

feat: Funcionalidade de Perfil. Close #161

---

apps/medicamentar-desktop/src/components/Loader.tsx
apps/medicamentar-desktop/src/components/Modals/ExamEditModal.tsx
apps/medicamentar-desktop/src/components/Modals/ExamModal.tsx
apps/medicamentar-desktop/src/components/Modals/ModalEditMedicine.tsx
apps/medicamentar-desktop/src/components/Modals/ModalNewMedication.tsx
apps/medicamentar-desktop/src/pages/Exam.tsx
apps/medicamentar-desktop/src/pages/Home.tsx
apps/medicamentar-desktop/src/pages/Medicine.tsx

Adiciona loader após requisições em componentes e páginas.
Reduz atrasos em requisições que antes tinham

feat: Adiciona loader em componentes/pages e reduz atrasos

---

apps/medicamentar-desktop/src/components/Modals/ModalEditMedicine.tsx
apps/medicamentar-desktop/src/components/Modals/ModalNewMedication.tsx
apps/medicamentar-desktop/src/pages/Exam.tsx
apps/medicamentar-desktop/src/pages/History.tsx

- Adiciona Loader em Histórico
- Simplifica states da página Exams
- Corrige algumas cores inconsistentes nos modais

Ajusta implementação do endpoint Consultation e Histórico closes #166

---

apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/dtos/consultationDto/ConsultationRequest.java

Remove a anotação de NotBlank no campo 'Descrição da Consulta'.

fix(MED-131): Remove a anotação de NotBlank.

---

apps/medicamentar-desktop/src/components/Modals/ExamEditModal.tsx
apps/medicamentar-desktop/src/pages/Profile.tsx

- Conserta o valor do input Endereço estar sendo inicializado como "null" ao criar conta e salvar sem inserir nada.
- Mudança no botão que, basicamente, altera o nome "EDITAR" para "SALVAR".

fix: Erro no valor do input "Endereço" | Mudança no botão de Salvar nos modais de editar. Close #220 #222

---

apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/api/controller/ConsultationController.java
apps/medicamentar-api/src/main/java/com/medicamentar/medicamentar_api/application/services/ConsultationService.java

Adiciona no Endpoint de Consulta o método "PUT".

fix(MED-139): Atualiza o Endpoint de Consulta

---

apps/medicamentar-desktop/src/components/Modals/ModalNewMedication.tsx

inicia variáveis de ophthalmologist, evitando que os valores fique nulo e quebre a aplicação.

fix: renderização de medicamentos
